// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HASCREEN_H
#define UI_HASCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HaScreen
extern void ui_HaScreen_screen_init(void);
extern void ui_HaScreen_screen_destroy(void);
/* 按系统语言刷新标题（0=中文 1=English），由 ui_lang 模块统一调用 */
extern void ui_HaScreen_apply_language(uint8_t lang);
extern void ui_event_HaScreen(lv_event_t * e);
extern lv_obj_t * ui_HaScreen;
extern lv_obj_t * ui_Label4;
extern void ui_event_ButtonLeft4(lv_event_t * e);
extern lv_obj_t * ui_ButtonLeft4;
extern void ui_event_ButtonRight4(lv_event_t * e);
extern lv_obj_t * ui_ButtonRight4;
extern void ui_event_ButtonEnter4(lv_event_t * e);
extern lv_obj_t * ui_ButtonEnter4;
extern lv_obj_t * ui_ButtonExit4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif