// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <stdint.h>

lv_obj_t *ui_MainScreen = NULL;
lv_obj_t *ui_ButtonLeft1 = NULL;
lv_obj_t *ui_ButtonRight1 = NULL;
lv_obj_t *ui_ButtonEnter1 = NULL;
lv_obj_t *ui_ButtonExit1 = NULL;
static lv_obj_t *s_ui_MainScreenProfileIconLabel = NULL;
static lv_obj_t *s_ui_MainScreenProfileIconImage = NULL;
static lv_obj_t *s_ui_MainScreenProfileName = NULL;
static lv_obj_t *s_ui_MainScreenHostConnectionIcon = NULL;
static lv_obj_t *s_ui_MainScreenHostConnectionLabel = NULL;
static bool s_ui_MainScreenHostConnected = false;
lv_obj_t *ui_LabelTime = NULL;
lv_obj_t *ui_LabelData = NULL;
lv_obj_t *ui_LabelSecond = NULL;
lv_obj_t *ui_LabelWeek = NULL;
lv_obj_t *ui_LabelWorkmode = NULL;
lv_obj_t *ui_LabelRGBLight = NULL;
lv_obj_t *ui_LabelTFTLight = NULL;
lv_obj_t *ui_line1 = NULL;
lv_obj_t *ui_line2 = NULL;
lv_obj_t *ui_line3 = NULL;
lv_obj_t *ui_line4 = NULL;
lv_obj_t *ui_line5 = NULL;
lv_obj_t *ui_line6 = NULL;

static void ui_MainScreen_refresh_host_connection(void)
{
    if (s_ui_MainScreenHostConnectionLabel != NULL)
    {
        lv_label_set_text(s_ui_MainScreenHostConnectionLabel, s_ui_MainScreenHostConnected ? "PC LINK" : "PC STOP");
        lv_obj_set_style_text_color(s_ui_MainScreenHostConnectionLabel,
                                    s_ui_MainScreenHostConnected ? lv_color_hex(0x22C55E) : lv_color_hex(0xF59E0B),
                                    LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    if (s_ui_MainScreenHostConnectionIcon != NULL)
    {
        lv_label_set_text(s_ui_MainScreenHostConnectionIcon,
                          s_ui_MainScreenHostConnected ? LV_SYMBOL_REFRESH : LV_SYMBOL_CLOSE);
        lv_obj_set_style_text_color(s_ui_MainScreenHostConnectionIcon,
                                    s_ui_MainScreenHostConnected ? lv_color_hex(0x22C55E) : lv_color_hex(0xF59E0B),
                                    LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}

// event funtions
void ui_event_MainScreen(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    uintptr_t key = (uintptr_t)lv_event_get_param(e);

    if (event_code == LV_EVENT_KEY && key == (uintptr_t)LV_KEY_RIGHT)
    {
        ui_set_active_screen_tag(UI_SCREEN_KEYMAPPED);
        _ui_screen_change(&ui_KeyMapped, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_KeyMapped_screen_init);
        lv_refr_now(NULL);
    }
    if (event_code == LV_EVENT_KEY && key == (uintptr_t)LV_KEY_LEFT)
    {
        _ui_screen_change(&ui_SettingScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_SettingScreen_screen_init);
        lv_refr_now(NULL);
    }
    // 主页 ENTER = 进入 KEYMAPPED（与旋钮单击对齐），ESC = 进入 SettingScreen（与双击对齐）
    if (event_code == LV_EVENT_KEY && key == (uintptr_t)LV_KEY_ENTER)
    {
        ui_set_active_screen_tag(UI_SCREEN_KEYMAPPED);
        _ui_screen_change(&ui_KeyMapped, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_KeyMapped_screen_init);
        lv_refr_now(NULL);
    }
    if (event_code == LV_EVENT_KEY && key == (uintptr_t)LV_KEY_ESC)
    {
        _ui_screen_change(&ui_SettingScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_SettingScreen_screen_init);
        lv_refr_now(NULL);
    }
}

void ui_event_ButtonLeft1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        // 获取当前屏幕及其聚焦对象
        lv_obj_t *active_screen = lv_scr_act();
        lv_group_t *g = lv_group_get_default();
        lv_obj_t *target = g ? lv_group_get_focused(g) : active_screen;

        // 发送按键事件
        if (target)
        {
            lv_event_send(target, LV_EVENT_KEY, (void *)LV_KEY_LEFT);
        }
    }
}

void ui_event_ButtonRight1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        // 获取当前屏幕及其聚焦对象
        lv_obj_t *active_screen = lv_scr_act();
        lv_group_t *g = lv_group_get_default();
        lv_obj_t *target = g ? lv_group_get_focused(g) : active_screen;

        // 发送按键事件
        if (target)
        {
            lv_event_send(target, LV_EVENT_KEY, (void *)LV_KEY_RIGHT);
        }
    }
}

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    ui_set_active_screen_tag(UI_SCREEN_MAIN);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_ButtonLeft1 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_ButtonLeft1, 41);
    lv_obj_set_height(ui_ButtonLeft1, 28);
    lv_obj_set_x(ui_ButtonLeft1, -178);
    lv_obj_set_y(ui_ButtonLeft1, -9);
    lv_obj_set_align(ui_ButtonLeft1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLeft1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_ButtonLeft1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_ButtonLeft1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonLeft1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRight1 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_ButtonRight1, 41);
    lv_obj_set_height(ui_ButtonRight1, 28);
    lv_obj_set_x(ui_ButtonRight1, 181);
    lv_obj_set_y(ui_ButtonRight1, -10);
    lv_obj_set_align(ui_ButtonRight1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRight1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_ButtonRight1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_ButtonRight1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRight1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonEnter1 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_ButtonEnter1, 41);
    lv_obj_set_height(ui_ButtonEnter1, 28);
    lv_obj_set_x(ui_ButtonEnter1, 2);
    lv_obj_set_y(ui_ButtonEnter1, 38);
    lv_obj_set_align(ui_ButtonEnter1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonEnter1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_ButtonEnter1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_ButtonEnter1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonEnter1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonExit1 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_ButtonExit1, 40);
    lv_obj_set_height(ui_ButtonExit1, 20);
    lv_obj_set_x(ui_ButtonExit1, -181);
    lv_obj_set_y(ui_ButtonExit1, -54);
    lv_obj_set_align(ui_ButtonExit1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonExit1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_ButtonExit1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_ButtonExit1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonExit1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_LabelTime, -18);
    lv_obj_set_y(ui_LabelTime, -24);
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "10:34");
    lv_obj_set_style_text_color(ui_LabelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTime, &ui_font_BebasNeueFont86, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelData = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelData, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LabelData, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_LabelData, 58);
    lv_obj_set_y(ui_LabelData, 36);
    lv_obj_set_align(ui_LabelData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelData, "SEP 05");
    lv_obj_set_style_text_color(ui_LabelData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelData, &ui_font_BebasNeueFont36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSecond = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelSecond, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LabelSecond, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_LabelSecond, 4);
    lv_obj_set_y(ui_LabelSecond, -6);
    lv_obj_align_to(ui_LabelSecond, ui_LabelTime, LV_ALIGN_OUT_RIGHT_BOTTOM, 4, -36);
    lv_label_set_text(ui_LabelSecond, "56");
    lv_obj_set_style_text_color(ui_LabelSecond, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSecond, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSecond, &ui_font_BebasNeueFont48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeek = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelWeek, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LabelWeek, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_LabelWeek, -40);
    lv_obj_set_y(ui_LabelWeek, 36);
    lv_obj_set_align(ui_LabelWeek, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWeek, "Monday");
    lv_obj_set_style_text_color(ui_LabelWeek, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeek, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeek, &ui_font_BebasNeueFont36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWorkmode = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelWorkmode, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LabelWorkmode, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_LabelWorkmode, -137);
    lv_obj_set_y(ui_LabelWorkmode, -39);
    lv_obj_set_align(ui_LabelWorkmode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWorkmode, "BLT MODE");
    lv_obj_set_style_text_color(ui_LabelWorkmode, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWorkmode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWorkmode, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_ui_MainScreenHostConnectionLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(s_ui_MainScreenHostConnectionLabel, 108);
    lv_obj_set_height(s_ui_MainScreenHostConnectionLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(s_ui_MainScreenHostConnectionLabel, -125);
    lv_obj_set_y(s_ui_MainScreenHostConnectionLabel, -4);
    lv_obj_set_align(s_ui_MainScreenHostConnectionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(s_ui_MainScreenHostConnectionLabel, "PC STOP");
    lv_label_set_long_mode(s_ui_MainScreenHostConnectionLabel, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_align(s_ui_MainScreenHostConnectionLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(s_ui_MainScreenHostConnectionLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_ui_MainScreenHostConnectionLabel, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_ui_MainScreenHostConnectionIcon = lv_label_create(ui_MainScreen);
    lv_obj_set_width(s_ui_MainScreenHostConnectionIcon, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(s_ui_MainScreenHostConnectionIcon, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(s_ui_MainScreenHostConnectionIcon, -125);
    lv_obj_set_y(s_ui_MainScreenHostConnectionIcon, 35);
    lv_obj_set_align(s_ui_MainScreenHostConnectionIcon, LV_ALIGN_CENTER);
    lv_label_set_text(s_ui_MainScreenHostConnectionIcon, LV_SYMBOL_REFRESH);
    lv_obj_set_style_text_opa(s_ui_MainScreenHostConnectionIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_ui_MainScreenHostConnectionIcon, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreen_refresh_host_connection();

    s_ui_MainScreenProfileIconLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(s_ui_MainScreenProfileIconLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(s_ui_MainScreenProfileIconLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(s_ui_MainScreenProfileIconLabel, -185);
    lv_obj_set_y(s_ui_MainScreenProfileIconLabel, 35);
    lv_obj_set_align(s_ui_MainScreenProfileIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(s_ui_MainScreenProfileIconLabel, LV_SYMBOL_LIST);
    lv_obj_set_style_text_color(s_ui_MainScreenProfileIconLabel, lv_color_hex(0xF5F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(s_ui_MainScreenProfileIconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_ui_MainScreenProfileIconLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_ui_MainScreenProfileIconImage = lv_img_create(ui_MainScreen);
    lv_obj_set_size(s_ui_MainScreenProfileIconImage, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_img_set_size_mode(s_ui_MainScreenProfileIconImage, LV_IMG_SIZE_MODE_REAL);
    lv_img_set_zoom(s_ui_MainScreenProfileIconImage, 192);
    lv_obj_set_x(s_ui_MainScreenProfileIconImage, -185);
    lv_obj_set_y(s_ui_MainScreenProfileIconImage, 35);
    lv_obj_set_align(s_ui_MainScreenProfileIconImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(s_ui_MainScreenProfileIconImage, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(s_ui_MainScreenProfileIconImage, LV_OBJ_FLAG_SCROLLABLE);

    s_ui_MainScreenProfileName = lv_label_create(ui_MainScreen);
    lv_obj_set_width(s_ui_MainScreenProfileName, 108);
    lv_obj_set_height(s_ui_MainScreenProfileName, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(s_ui_MainScreenProfileName, -185);
    lv_obj_set_y(s_ui_MainScreenProfileName, -4);
    lv_obj_set_align(s_ui_MainScreenProfileName, LV_ALIGN_CENTER);
    lv_label_set_text(s_ui_MainScreenProfileName, "CONF1");
    lv_label_set_long_mode(s_ui_MainScreenProfileName, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_align(s_ui_MainScreenProfileName, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(s_ui_MainScreenProfileName, lv_color_hex(0xF59E0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(s_ui_MainScreenProfileName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_ui_MainScreenProfileName, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRGBLight = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelRGBLight, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LabelRGBLight, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_LabelRGBLight, 155);
    lv_obj_set_y(ui_LabelRGBLight, -50);
    lv_obj_set_align(ui_LabelRGBLight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRGBLight, "RGB 75%");
    lv_obj_set_style_text_color(ui_LabelRGBLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelRGBLight, &ui_font_BebasNeueFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTFTLight = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelTFTLight, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LabelTFTLight, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_LabelTFTLight, 155);
    lv_obj_set_y(ui_LabelTFTLight, -32);
    lv_obj_set_align(ui_LabelTFTLight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTFTLight, "TFT 75%");
    lv_obj_set_style_text_color(ui_LabelTFTLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTFTLight, &ui_font_BebasNeueFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyMappedSecondary_bind_main_screen_summary(s_ui_MainScreenProfileIconLabel,
                                                   s_ui_MainScreenProfileIconImage,
                                                   s_ui_MainScreenProfileName);

    ui_line1 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_line1, 108);
    lv_obj_set_height(ui_line1, 1);
    lv_obj_set_x(ui_line1, -152);
    lv_obj_set_y(ui_line1, -26);
    lv_obj_set_align(ui_line1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_line1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_line2 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_line2, 1);
    lv_obj_set_height(ui_line2, 60);
    lv_obj_set_x(ui_line2, -159);
    lv_obj_set_y(ui_line2, 18);
    lv_obj_set_align(ui_line2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_line2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_line3 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_line3, 186);
    lv_obj_set_height(ui_line3, 1);
    lv_obj_set_x(ui_line3, 3);
    lv_obj_set_y(ui_line3, 13);
    lv_obj_set_align(ui_line3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_line3, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_line4 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_line4, 92);
    lv_obj_set_height(ui_line4, 1);
    lv_obj_set_x(ui_line4, 155);
    lv_obj_set_y(ui_line4, -25);
    lv_obj_set_align(ui_line4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_line4, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_line6 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_line6, 1);
    lv_obj_set_height(ui_line6, 60);
    lv_obj_set_x(ui_line6, 156);
    lv_obj_set_y(ui_line6, 18);
    lv_obj_set_align(ui_line6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_line6, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    lv_obj_add_event_cb(ui_ButtonLeft1, ui_event_ButtonLeft1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRight1, ui_event_ButtonRight1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);
}

void ui_MainScreen_set_work_mode(char *mode)
{
    lv_label_set_text(ui_LabelWorkmode, mode);
}

void ui_MainScreen_set_rgb_light(uint8_t percent)
{
    if (ui_LabelRGBLight != NULL)
    {
        lv_label_set_text_fmt(ui_LabelRGBLight, "RGB %u%%", (unsigned)percent);
    }
}

void ui_MainScreen_set_tft_light(uint8_t percent)
{
    if (ui_LabelTFTLight != NULL)
    {
        lv_label_set_text_fmt(ui_LabelTFTLight, "TFT %u%%", (unsigned)percent);
    }
}

void ui_MainScreen_set_host_connection(bool connected)
{
    s_ui_MainScreenHostConnected = connected;
    ui_MainScreen_refresh_host_connection();
}

void ui_MainScreen_screen_destroy(void)
{
    ui_KeyMappedSecondary_bind_main_screen_summary(NULL, NULL, NULL);
    if (ui_MainScreen)
        lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_ButtonLeft1 = NULL;
    ui_ButtonRight1 = NULL;
    ui_ButtonEnter1 = NULL;
    ui_ButtonExit1 = NULL;
    s_ui_MainScreenProfileIconLabel = NULL;
    s_ui_MainScreenProfileIconImage = NULL;
    s_ui_MainScreenProfileName = NULL;
    s_ui_MainScreenHostConnectionIcon = NULL;
    s_ui_MainScreenHostConnectionLabel = NULL;
    ui_LabelTime = NULL;
    ui_LabelData = NULL;
    ui_LabelSecond = NULL;
    ui_LabelWeek = NULL;
    ui_LabelWorkmode = NULL;
    ui_LabelRGBLight = NULL;
    ui_LabelTFTLight = NULL;
    ui_line1 = NULL;
    ui_line2 = NULL;
    ui_line3 = NULL;
    ui_line4 = NULL;
    ui_line5 = NULL;
    ui_line6 = NULL;
}
