// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_FlipClock.h"
#include "ui_StatusBar.h" /* 工作模式枚举 WIRED/BLUETOOTH/WIRELESS_2_4G_KEYBOARD_MODE */
#include <stdint.h>

lv_obj_t *ui_MainScreen = NULL;
lv_obj_t *ui_ButtonLeft1 = NULL;
lv_obj_t *ui_ButtonRight1 = NULL;
lv_obj_t *ui_ButtonEnter1 = NULL;
lv_obj_t *ui_ButtonExit1 = NULL;
static lv_obj_t *s_ui_MainScreenProfileIconLabel = NULL;
static lv_obj_t *s_ui_MainScreenProfileIconImage = NULL;
static lv_obj_t *s_ui_MainScreenProfileName = NULL;
static lv_obj_t *s_ui_MainScreenHostConnectionIcon = NULL;
static lv_obj_t *s_ui_MainScreenWorkmodeIcon = NULL;
static bool s_ui_MainScreenHostConnected = false;
lv_obj_t *ui_LabelData = NULL;
lv_obj_t *ui_LabelWeek = NULL;

/*
 * 主页连接状态：只显示图标（已移除 PC LINK / PC STOP 文本）。
 * 键盘主机（BLE/USB）已连接 → 白色；未连接 → 橙色。
 */
static void ui_MainScreen_refresh_host_connection(void)
{
    if (s_ui_MainScreenHostConnectionIcon != NULL)
    {
        lv_label_set_text(s_ui_MainScreenHostConnectionIcon,
                          s_ui_MainScreenHostConnected ? LV_SYMBOL_REFRESH : LV_SYMBOL_CLOSE);
        lv_obj_set_style_text_color(s_ui_MainScreenHostConnectionIcon,
                                    s_ui_MainScreenHostConnected ? lv_color_hex(0xFFFFFF) : lv_color_hex(0xF59E0B),
                                    LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}

// event funtions
void ui_event_MainScreen(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    uintptr_t key = (uintptr_t)lv_event_get_param(e);

    if (event_code == LV_EVENT_KEY && key == (uintptr_t)LV_KEY_RIGHT)
    {
        ui_set_active_screen_tag(UI_SCREEN_KEYMAPPED);
        _ui_screen_change(&ui_KeyMapped, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_KeyMapped_screen_init);
        lv_refr_now(NULL);
    }
    if (event_code == LV_EVENT_KEY && key == (uintptr_t)LV_KEY_LEFT)
    {
        ui_set_active_screen_tag(UI_SCREEN_SETTING);
        _ui_screen_change(&ui_SettingScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_SettingScreen_screen_init);
        lv_refr_now(NULL);
    }
    // 主页旋钮单击（ENTER）= 无操作；ESC = 进入 SettingScreen（与双击对齐）
    if (event_code == LV_EVENT_KEY && key == (uintptr_t)LV_KEY_ESC)
    {
        ui_set_active_screen_tag(UI_SCREEN_SETTING);
        _ui_screen_change(&ui_SettingScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_SettingScreen_screen_init);
        lv_refr_now(NULL);
    }
}

void ui_event_ButtonLeft1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        // 获取当前屏幕及其聚焦对象
        lv_obj_t *active_screen = lv_scr_act();
        lv_group_t *g = lv_group_get_default();
        lv_obj_t *target = g ? lv_group_get_focused(g) : active_screen;

        // 发送按键事件
        if (target)
        {
            lv_event_send(target, LV_EVENT_KEY, (void *)LV_KEY_LEFT);
        }
    }
}

void ui_event_ButtonRight1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        // 获取当前屏幕及其聚焦对象
        lv_obj_t *active_screen = lv_scr_act();
        lv_group_t *g = lv_group_get_default();
        lv_obj_t *target = g ? lv_group_get_focused(g) : active_screen;

        // 发送按键事件
        if (target)
        {
            lv_event_send(target, LV_EVENT_KEY, (void *)LV_KEY_RIGHT);
        }
    }
}

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    ui_set_active_screen_tag(UI_SCREEN_MAIN);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_ButtonLeft1 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_ButtonLeft1, 41);
    lv_obj_set_height(ui_ButtonLeft1, 28);
    lv_obj_set_x(ui_ButtonLeft1, -178);
    lv_obj_set_y(ui_ButtonLeft1, -9);
    lv_obj_set_align(ui_ButtonLeft1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLeft1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_ButtonLeft1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_ButtonLeft1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonLeft1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRight1 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_ButtonRight1, 41);
    lv_obj_set_height(ui_ButtonRight1, 28);
    lv_obj_set_x(ui_ButtonRight1, 181);
    lv_obj_set_y(ui_ButtonRight1, -10);
    lv_obj_set_align(ui_ButtonRight1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRight1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_ButtonRight1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_ButtonRight1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRight1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonEnter1 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_ButtonEnter1, 41);
    lv_obj_set_height(ui_ButtonEnter1, 28);
    lv_obj_set_x(ui_ButtonEnter1, 2);
    lv_obj_set_y(ui_ButtonEnter1, 38);
    lv_obj_set_align(ui_ButtonEnter1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonEnter1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_ButtonEnter1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_ButtonEnter1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonEnter1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonExit1 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_ButtonExit1, 40);
    lv_obj_set_height(ui_ButtonExit1, 20);
    lv_obj_set_x(ui_ButtonExit1, -181);
    lv_obj_set_y(ui_ButtonExit1, -54);
    lv_obj_set_align(ui_ButtonExit1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonExit1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_ButtonExit1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_ButtonExit1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonExit1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* ---------- 中部：翻页时钟（HH:MM 大卡片 + 秒小卡片，见 ui_FlipClock.c） ---------- */
    ui_FlipClock_create(ui_MainScreen);

    /* ---------- 底部：分隔线 + 图标/日期星期/键盘配置（单行，y 99~142） ---------- */
    {
        lv_obj_t *divider = lv_obj_create(ui_MainScreen);
        lv_obj_remove_style_all(divider);
        lv_obj_set_pos(divider, 10, 99);
        lv_obj_set_size(divider, 408, 1);
        lv_obj_set_style_bg_color(divider, lv_color_hex(0x333333), 0);
        lv_obj_set_style_bg_opa(divider, LV_OPA_COVER, 0);
    }

    ui_LabelData = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelData, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LabelData, LV_SIZE_CONTENT); /// 1
    lv_obj_align(ui_LabelData, LV_ALIGN_TOP_MID, -10, 108);
    lv_label_set_text(ui_LabelData, "09月14日");
    lv_obj_set_style_text_color(ui_LabelData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelData, &ui_font_FontCKJGT16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeek = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelWeek, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LabelWeek, LV_SIZE_CONTENT); /// 1
    /* 星期紧跟日期右侧（日期文本宽度变化时相对关系保持），同字号同色 */
    lv_obj_align_to(ui_LabelWeek, ui_LabelData, LV_ALIGN_OUT_RIGHT_BOTTOM, 6, 0);
    lv_label_set_text(ui_LabelWeek, "星期一");
    lv_obj_set_style_text_color(ui_LabelWeek, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeek, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeek, &ui_font_FontCKJGT16, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* ---------- 底部左侧：工作模式图标（有线/蓝牙/2.4G） + 主机连接状态 ---------- */
    s_ui_MainScreenWorkmodeIcon = lv_label_create(ui_MainScreen);
    lv_obj_set_style_text_font(s_ui_MainScreenWorkmodeIcon, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(s_ui_MainScreenWorkmodeIcon, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(s_ui_MainScreenWorkmodeIcon, LV_SYMBOL_USB);
    lv_obj_align(s_ui_MainScreenWorkmodeIcon, LV_ALIGN_TOP_LEFT, 8, 106);

    /* 工作模式文字（BLT/WIR MODE）已删除：底部左列图标已表达模式 */

    /* 连接状态：只保留图标（底部，工作模式图标右侧） */
    s_ui_MainScreenHostConnectionIcon = lv_label_create(ui_MainScreen);
    lv_obj_set_width(s_ui_MainScreenHostConnectionIcon, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(s_ui_MainScreenHostConnectionIcon, LV_SIZE_CONTENT); /// 1
    lv_obj_align(s_ui_MainScreenHostConnectionIcon, LV_ALIGN_TOP_LEFT, 32, 104);
    lv_label_set_text(s_ui_MainScreenHostConnectionIcon, LV_SYMBOL_CLOSE);
    lv_obj_set_style_text_opa(s_ui_MainScreenHostConnectionIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_ui_MainScreenHostConnectionIcon, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreen_refresh_host_connection();

    s_ui_MainScreenProfileIconLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(s_ui_MainScreenProfileIconLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(s_ui_MainScreenProfileIconLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_align(s_ui_MainScreenProfileIconLabel, LV_ALIGN_TOP_LEFT, 300, 106);
    lv_label_set_text(s_ui_MainScreenProfileIconLabel, LV_SYMBOL_LIST);
    lv_obj_set_style_text_color(s_ui_MainScreenProfileIconLabel, lv_color_hex(0xF5F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(s_ui_MainScreenProfileIconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_ui_MainScreenProfileIconLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_ui_MainScreenProfileIconImage = lv_img_create(ui_MainScreen);
    lv_obj_set_size(s_ui_MainScreenProfileIconImage, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_img_set_size_mode(s_ui_MainScreenProfileIconImage, LV_IMG_SIZE_MODE_REAL);
    lv_img_set_zoom(s_ui_MainScreenProfileIconImage, 100); /* 原始 48px 图标缩到 ~19px 适配底栏行高 */
    lv_obj_align(s_ui_MainScreenProfileIconImage, LV_ALIGN_TOP_LEFT, 294, 102);
    lv_obj_add_flag(s_ui_MainScreenProfileIconImage, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(s_ui_MainScreenProfileIconImage, LV_OBJ_FLAG_SCROLLABLE);

    s_ui_MainScreenProfileName = lv_label_create(ui_MainScreen);
    lv_obj_set_width(s_ui_MainScreenProfileName, 98);
    lv_obj_set_height(s_ui_MainScreenProfileName, LV_SIZE_CONTENT); /// 1
    lv_obj_align(s_ui_MainScreenProfileName, LV_ALIGN_TOP_RIGHT, -8, 106);
    lv_label_set_text(s_ui_MainScreenProfileName, "CONF1");
    lv_label_set_long_mode(s_ui_MainScreenProfileName, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_align(s_ui_MainScreenProfileName, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(s_ui_MainScreenProfileName, lv_color_hex(0xF59E0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(s_ui_MainScreenProfileName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    /* Profile 名称可能为 APP 下发的中文（UTF-8），用 CKJGT 中文字体渲染；
     * 中文全高字形偏大，降为 16 号与 PC 状态文字视觉协调 */
    lv_obj_set_style_text_font(s_ui_MainScreenProfileName, &ui_font_FontCKJGT16, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* WiFi 状态仅在 ui_StatusBar 中显示，主页不再渲染 */

    ui_KeyMappedSecondary_bind_main_screen_summary(s_ui_MainScreenProfileIconLabel,
                                                   s_ui_MainScreenProfileIconImage,
                                                   s_ui_MainScreenProfileName);

    lv_obj_add_event_cb(ui_ButtonLeft1, ui_event_ButtonLeft1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRight1, ui_event_ButtonRight1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);
}

/*
 * 日期 + 星期文本更新：星期相对日期右侧对齐，而日期文本宽度随语言
 * 切换变化（中文"09月14日" ↔ 英文"SEP 08"），lv_obj_align_to 是一次性
 * 布局，因此每次更新文本后必须重新对齐，否则星期位置脱离日期。
 * 空字段跳过（未同步时避免覆盖初始占位）。
 */
void ui_MainScreen_set_date_week(const char *date, const char *week)
{
    if (ui_LabelData == NULL || ui_LabelWeek == NULL)
    {
        return;
    }
    if (date != NULL && date[0] != '\0')
    {
        lv_label_set_text(ui_LabelData, date);
    }
    if (week != NULL && week[0] != '\0')
    {
        lv_label_set_text(ui_LabelWeek, week);
    }
    lv_obj_update_layout(ui_LabelData); /* 先落定新文本宽度再取对齐坐标 */
    lv_obj_align_to(ui_LabelWeek, ui_LabelData, LV_ALIGN_OUT_RIGHT_BOTTOM, 6, 0);
}

/* 工作模式图标：有线 → USB，蓝牙 → BT，2.4G → DRIVE（由 DisplayTask 推送） */
void ui_MainScreen_set_working_mode(int mode)
{
    if (s_ui_MainScreenWorkmodeIcon == NULL)
    {
        return;
    }
    switch (mode)
    {
    case WIRED_KEYBOARD_MODE:
        lv_label_set_text(s_ui_MainScreenWorkmodeIcon, LV_SYMBOL_USB);
        break;
    case BLUETOOTH_KEYBOARD_MODE:
        lv_label_set_text(s_ui_MainScreenWorkmodeIcon, LV_SYMBOL_BLUETOOTH);
        break;
    case WIRELESS_2_4G_KEYBOARD_MODE:
        lv_label_set_text(s_ui_MainScreenWorkmodeIcon, LV_SYMBOL_DRIVE);
        break;
    default:
        break;
    }
}

void ui_MainScreen_set_host_connection(bool connected)
{
    s_ui_MainScreenHostConnected = connected;
    ui_MainScreen_refresh_host_connection();
}

void ui_MainScreen_screen_destroy(void)
{
    ui_KeyMappedSecondary_bind_main_screen_summary(NULL, NULL, NULL);
    ui_FlipClock_destroy();
    if (ui_MainScreen)
        lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_ButtonLeft1 = NULL;
    ui_ButtonRight1 = NULL;
    ui_ButtonEnter1 = NULL;
    ui_ButtonExit1 = NULL;
    s_ui_MainScreenProfileIconLabel = NULL;
    s_ui_MainScreenProfileIconImage = NULL;
    s_ui_MainScreenProfileName = NULL;
    s_ui_MainScreenHostConnectionIcon = NULL;
    s_ui_MainScreenWorkmodeIcon = NULL;
    ui_LabelData = NULL;
    ui_LabelWeek = NULL;
}
