// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C"
{
#endif

  // SCREEN: ui_MainScreen
  extern void ui_MainScreen_screen_init(void);
  extern void ui_MainScreen_screen_destroy(void);
  extern void ui_MainScreen_set_working_mode(int mode);
  extern void ui_MainScreen_set_host_connection(bool connected);
  extern void ui_MainScreen_set_date_week(const char *date, const char *week);
  extern void ui_event_MainScreen(lv_event_t *e);
  extern lv_obj_t *ui_MainScreen;
  extern void ui_event_ButtonLeft1(lv_event_t *e);
  extern lv_obj_t *ui_ButtonLeft1;
  extern void ui_event_ButtonRight1(lv_event_t *e);
  extern lv_obj_t *ui_ButtonRight1;
  extern lv_obj_t *ui_ButtonEnter1;
  extern lv_obj_t *ui_ButtonExit1;
  extern lv_obj_t *ui_LabelData;
  extern lv_obj_t *ui_LabelWeek;
  // CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif