// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

lv_obj_t *ui_PcStatusScreenSecondary = NULL;
lv_obj_t *ui_Label2 = NULL;
lv_obj_t *ui_LabelPcHost = NULL;
lv_obj_t *ui_LabelPcTime = NULL;
lv_obj_t *ui_LabelPcLocks = NULL;
lv_obj_t *ui_LabelPcNetwork = NULL;
lv_obj_t *ui_LabelPcPower = NULL;
static lv_obj_t *s_LabelPcPerf = NULL;
static lv_obj_t *s_LabelPcTemp = NULL;

static lv_obj_t *s_PanelLeft = NULL;
static lv_obj_t *s_PanelRight = NULL;
static lv_obj_t *s_LabelTimeValue = NULL;
static lv_obj_t *s_LabelNetValue = NULL;
static lv_obj_t *s_LabelUpValue = NULL;
static lv_obj_t *s_LabelDownValue = NULL;
static lv_obj_t *s_LabelCpuValue = NULL;
static lv_obj_t *s_LabelCpuTempValue = NULL;
static lv_obj_t *s_LabelMemValue = NULL;
static lv_obj_t *s_LabelDiskValue = NULL;
static lv_obj_t *s_NetDot = NULL;
static lv_obj_t *s_BarCpu = NULL;
static lv_obj_t *s_BarCpuTemp = NULL;
static lv_obj_t *s_BarMem = NULL;
static lv_obj_t *s_BarDisk = NULL;
static lv_obj_t *s_ButtonLeft = NULL;
static lv_obj_t *s_ButtonRight = NULL;
static lv_obj_t *s_ButtonEnter = NULL;
static lv_obj_t *s_ButtonExit = NULL;

/*
 * 字段缓存：<0 表示"未同步"，回退占位文本由 setter 内部决定。
 * pc_status_apply_cached_values() 在二级屏 init 末尾回放，
 * 避免从主屏 ENTER 进入二级屏时空白。
 */
static struct
{
    bool valid;
    bool network_connected;
    float net_up_kbps;
    float net_down_kbps;
    float cpu_percent;
    float cpu_temp_c;
    float mem_percent;
    float disk_io_percent;
} s_cached = {false, false,
              -1.0f, -1.0f, -1.0f, -1.0f, -1.0f, -1.0f};

static void pc_status_set_bar_value(lv_obj_t *bar, float pct)
{
    if (!bar)
    {
        return;
    }
    if (pct < 0.0f)
    {
        lv_bar_set_value(bar, 0, LV_ANIM_OFF);
    }
    else
    {
        if (pct > 100.0f)
            pct = 100.0f;
        lv_bar_set_value(bar, (int)(pct + 0.5f), LV_ANIM_ON);
    }
}

static void pc_status_apply_cached_values(void)
{
    if (!s_cached.valid)
        return;
    ui_PcStatusScreen_set_network(s_cached.network_connected);
    ui_PcStatusScreen_set_net_up_kbps(s_cached.net_up_kbps);
    ui_PcStatusScreen_set_net_down_kbps(s_cached.net_down_kbps);
    ui_PcStatusScreen_set_cpu_percent(s_cached.cpu_percent);
    ui_PcStatusScreen_set_cpu_temp_c(s_cached.cpu_temp_c);
    ui_PcStatusScreen_set_mem_percent(s_cached.mem_percent);
    ui_PcStatusScreen_set_disk_io_percent(s_cached.disk_io_percent);
}

static void pc_status_secondary_forward_key(uint32_t key)
{
    lv_obj_t *active_screen = lv_scr_act();
    lv_group_t *g = lv_group_get_default();
    lv_obj_t *target = g ? lv_group_get_focused(g) : active_screen;
    if (target)
    {
        lv_event_send(target, LV_EVENT_KEY, (void *)key);
    }
}

/*
 * Locks setter（已删除）：
 *   早期实现保留了 caps_lock / num_lock / scroll_lock 的协议解析与缓存，
 *   但二级屏布局无对应控件。任务 #2 决定三处一致删除。
 */

void ui_PcStatusScreen_set_network(bool connected)
{
    s_cached.valid = true;
    s_cached.network_connected = connected;
    if (!s_LabelNetValue || !s_NetDot)
        return;

    lv_label_set_text(s_LabelNetValue, connected ? "ONLINE" : "OFFLINE");
    lv_obj_set_style_bg_color(s_NetDot,
                              connected ? lv_color_hex(0x22C55E)
                                        : lv_color_hex(0xEF4444),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_PcStatusScreen_set_net_up_kbps(float kbps)
{
    char buf[24];
    s_cached.valid = true;
    s_cached.net_up_kbps = kbps;
    if (!s_LabelUpValue)
        return;

    if (kbps < 0.0f)
    {
        lv_label_set_text(s_LabelUpValue, "-- Kbps");
    }
    else
    {
        snprintf(buf, sizeof(buf), "%.1f Kbps", kbps);
        lv_label_set_text(s_LabelUpValue, buf);
    }
}

void ui_PcStatusScreen_set_net_down_kbps(float kbps)
{
    char buf[24];
    s_cached.valid = true;
    s_cached.net_down_kbps = kbps;
    if (!s_LabelDownValue)
        return;

    if (kbps < 0.0f)
    {
        lv_label_set_text(s_LabelDownValue, "-- Kbps");
    }
    else
    {
        snprintf(buf, sizeof(buf), "%.1f Kbps", kbps);
        lv_label_set_text(s_LabelDownValue, buf);
    }
}

void ui_PcStatusScreen_set_cpu_percent(float pct)
{
    char buf[16];
    s_cached.valid = true;
    s_cached.cpu_percent = pct;
    if (!s_LabelCpuValue || !s_BarCpu)
        return;

    if (pct < 0.0f)
    {
        lv_label_set_text(s_LabelCpuValue, "--");
    }
    else
    {
        snprintf(buf, sizeof(buf), "%.1f%%", pct);
        lv_label_set_text(s_LabelCpuValue, buf);
    }
    pc_status_set_bar_value(s_BarCpu, pct);
}

void ui_PcStatusScreen_set_cpu_temp_c(float c)
{
    char buf[16];
    s_cached.valid = true;
    s_cached.cpu_temp_c = c;
    if (!s_LabelCpuTempValue || !s_BarCpuTemp)
        return;

    if (c < 0.0f)
    {
        lv_label_set_text(s_LabelCpuTempValue, "N/A");
    }
    else
    {
        snprintf(buf, sizeof(buf), "%.1fC", c);
        lv_label_set_text(s_LabelCpuTempValue, buf);
    }
    /*
     * CPU 温度没有自然的 0~100 区间，沿用旧实现：把摄氏度钳到 0~100 当指示器长度。
     * 视觉上 50℃ 大约一半，与"越热越长"语义基本一致。
     */
    pc_status_set_bar_value(s_BarCpuTemp, c);
}

void ui_PcStatusScreen_set_mem_percent(float pct)
{
    char buf[16];
    s_cached.valid = true;
    s_cached.mem_percent = pct;
    if (!s_LabelMemValue || !s_BarMem)
        return;

    if (pct < 0.0f)
    {
        lv_label_set_text(s_LabelMemValue, "--");
    }
    else
    {
        snprintf(buf, sizeof(buf), "%.1f%%", pct);
        lv_label_set_text(s_LabelMemValue, buf);
    }
    pc_status_set_bar_value(s_BarMem, pct);
}

void ui_PcStatusScreen_set_disk_io_percent(float pct)
{
    char buf[16];
    s_cached.valid = true;
    s_cached.disk_io_percent = pct;
    if (!s_LabelDiskValue || !s_BarDisk)
        return;

    if (pct < 0.0f)
    {
        lv_label_set_text(s_LabelDiskValue, "--");
    }
    else
    {
        snprintf(buf, sizeof(buf), "%.1f%%", pct);
        lv_label_set_text(s_LabelDiskValue, buf);
    }
    pc_status_set_bar_value(s_BarDisk, pct);
}

void ui_event_PcStatusScreenSecondary(lv_event_t *e)
{
    if (lv_event_get_code(e) != LV_EVENT_KEY)
    {
        return;
    }

    if ((uintptr_t)lv_event_get_param(e) == (uintptr_t)LV_KEY_ESC)
    {
        ui_set_active_screen_tag(UI_SCREEN_PC_STATUS);
        _ui_screen_change(&ui_PcStatusScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_PcStatusScreen_screen_init);
        lv_refr_now(NULL);
    }
}

void ui_event_ButtonExitPcStatusSecondary(lv_event_t *e)
{
    if (lv_event_get_code(e) == LV_EVENT_CLICKED)
    {
        pc_status_secondary_forward_key(LV_KEY_ESC);
    }
}

void ui_PcStatusScreenSecondary_screen_init(void)
{
    ui_PcStatusScreenSecondary = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PcStatusScreenSecondary, LV_OBJ_FLAG_SCROLLABLE);

    ui_Label2 = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 2);
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label2, "PC STATUS");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x6ADAE1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_PanelLeft = NULL;
    s_PanelRight = NULL;

    lv_obj_t *labelTime = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(labelTime, 10, 26);
    lv_label_set_text(labelTime, "TIME");
    lv_obj_set_style_text_color(labelTime, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelTime, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelTimeValue = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(s_LabelTimeValue, 76, 26);
    lv_obj_set_width(s_LabelTimeValue, 150);
    lv_label_set_long_mode(s_LabelTimeValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(s_LabelTimeValue, "--:--:--");
    lv_obj_set_style_text_color(s_LabelTimeValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelTimeValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *labelNet = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(labelNet, 10, 50);
    lv_label_set_text(labelNet, "NET");
    lv_obj_set_style_text_color(labelNet, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelNet, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_NetDot = lv_obj_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_NetDot, 10, 10);
    lv_obj_set_pos(s_NetDot, 56, 56);
    lv_obj_set_style_radius(s_NetDot, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(s_NetDot, lv_color_hex(0xEF4444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(s_NetDot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelNetValue = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(s_LabelNetValue, 76, 50);
    lv_obj_set_width(s_LabelNetValue, 144);
    lv_label_set_long_mode(s_LabelNetValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(s_LabelNetValue, "OFFLINE");
    lv_obj_set_style_text_color(s_LabelNetValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelNetValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *labelUp = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(labelUp, 10, 74);
    lv_label_set_text(labelUp, "UP");
    lv_obj_set_style_text_color(labelUp, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelUp, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelUpValue = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(s_LabelUpValue, 76, 74);
    lv_obj_set_width(s_LabelUpValue, 160);
    lv_label_set_long_mode(s_LabelUpValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(s_LabelUpValue, "-- Kbps");
    lv_obj_set_style_text_color(s_LabelUpValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelUpValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *labelDown = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(labelDown, 10, 98);
    lv_label_set_text(labelDown, "DOWN");
    lv_obj_set_style_text_color(labelDown, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelDown, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelDownValue = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(s_LabelDownValue, 76, 98);
    lv_obj_set_width(s_LabelDownValue, 160);
    lv_label_set_long_mode(s_LabelDownValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(s_LabelDownValue, "-- Kbps");
    lv_obj_set_style_text_color(s_LabelDownValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelDownValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *labelCpu = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(labelCpu, 244, 26);
    lv_label_set_text(labelCpu, "CPU");
    lv_obj_set_style_text_color(labelCpu, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelCpu, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelCpuValue = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(s_LabelCpuValue, 308, 26);
    lv_obj_set_width(s_LabelCpuValue, 50);
    lv_label_set_long_mode(s_LabelCpuValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(s_LabelCpuValue, "--");
    lv_obj_set_style_text_color(s_LabelCpuValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelCpuValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_BarCpu = lv_bar_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_BarCpu, 60, 10);
    lv_obj_set_pos(s_BarCpu, 365, 34);
    lv_bar_set_range(s_BarCpu, 0, 100);
    lv_obj_set_style_bg_color(s_BarCpu, lv_color_hex(0x374151), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(s_BarCpu, lv_color_hex(0x22C55E), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_t *labelCpuTemp = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(labelCpuTemp, 244, 50);
    lv_label_set_text(labelCpuTemp, "CPU-T");
    lv_obj_set_style_text_color(labelCpuTemp, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelCpuTemp, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelCpuTempValue = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(s_LabelCpuTempValue, 308, 50);
    lv_obj_set_width(s_LabelCpuTempValue, 70);
    lv_label_set_long_mode(s_LabelCpuTempValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(s_LabelCpuTempValue, "N/A");
    lv_obj_set_style_text_color(s_LabelCpuTempValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelCpuTempValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_BarCpuTemp = lv_bar_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_BarCpuTemp, 60, 10);
    lv_obj_set_pos(s_BarCpuTemp, 365, 58);
    lv_bar_set_range(s_BarCpuTemp, 0, 100);
    lv_bar_set_value(s_BarCpuTemp, 0, LV_ANIM_OFF);
    lv_obj_set_style_bg_color(s_BarCpuTemp, lv_color_hex(0x374151), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(s_BarCpuTemp, lv_color_hex(0xEF4444), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_t *labelMem = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(labelMem, 244, 74);
    lv_label_set_text(labelMem, "MEM");
    lv_obj_set_style_text_color(labelMem, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelMem, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelMemValue = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(s_LabelMemValue, 308, 74);
    lv_obj_set_width(s_LabelMemValue, 50);
    lv_label_set_long_mode(s_LabelMemValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(s_LabelMemValue, "--");
    lv_obj_set_style_text_color(s_LabelMemValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelMemValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_BarMem = lv_bar_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_BarMem, 60, 10);
    lv_obj_set_pos(s_BarMem, 365, 86);
    lv_bar_set_range(s_BarMem, 0, 100);
    lv_obj_set_style_bg_color(s_BarMem, lv_color_hex(0x374151), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(s_BarMem, lv_color_hex(0x3B82F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_t *labelDisk = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(labelDisk, 244, 98);
    lv_label_set_text(labelDisk, "D-IO");
    lv_obj_set_style_text_color(labelDisk, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelDisk, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelDiskValue = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(s_LabelDiskValue, 308, 98);
    lv_obj_set_width(s_LabelDiskValue, 50);
    lv_label_set_long_mode(s_LabelDiskValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(s_LabelDiskValue, "--");
    lv_obj_set_style_text_color(s_LabelDiskValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelDiskValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_BarDisk = lv_bar_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_BarDisk, 60, 10);
    lv_obj_set_pos(s_BarDisk, 365, 114);
    lv_bar_set_range(s_BarDisk, 0, 100);
    lv_obj_set_style_bg_color(s_BarDisk, lv_color_hex(0x374151), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(s_BarDisk, lv_color_hex(0xF59E0B), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelPcHost = s_LabelTimeValue;
    ui_LabelPcTime = s_LabelNetValue;
    ui_LabelPcLocks = s_LabelUpValue;
    ui_LabelPcNetwork = s_LabelDownValue;
    ui_LabelPcPower = s_LabelCpuValue;
    s_LabelPcPerf = s_LabelMemValue;
    s_LabelPcTemp = s_LabelDiskValue;

    s_ButtonLeft = lv_btn_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_ButtonLeft, 41, 28);
    lv_obj_set_align(s_ButtonLeft, LV_ALIGN_CENTER);
    lv_obj_set_pos(s_ButtonLeft, -178, -9);
    lv_obj_set_style_bg_opa(s_ButtonLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(s_ButtonLeft, LV_OBJ_FLAG_SCROLLABLE);

    s_ButtonRight = lv_btn_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_ButtonRight, 41, 28);
    lv_obj_set_align(s_ButtonRight, LV_ALIGN_CENTER);
    lv_obj_set_pos(s_ButtonRight, 181, -10);
    lv_obj_set_style_bg_opa(s_ButtonRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(s_ButtonRight, LV_OBJ_FLAG_SCROLLABLE);

    s_ButtonEnter = lv_btn_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_ButtonEnter, 41, 28);
    lv_obj_set_align(s_ButtonEnter, LV_ALIGN_CENTER);
    lv_obj_set_pos(s_ButtonEnter, 2, 38);
    lv_obj_set_style_bg_opa(s_ButtonEnter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(s_ButtonEnter, LV_OBJ_FLAG_SCROLLABLE);

    s_ButtonExit = lv_btn_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_ButtonExit, 40, 20);
    lv_obj_set_align(s_ButtonExit, LV_ALIGN_CENTER);
    lv_obj_set_pos(s_ButtonExit, -181, -54);
    lv_obj_set_style_bg_opa(s_ButtonExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(s_ButtonExit, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_add_event_cb(s_ButtonExit, ui_event_ButtonExitPcStatusSecondary, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PcStatusScreenSecondary, ui_event_PcStatusScreenSecondary, LV_EVENT_ALL, NULL);

    pc_status_apply_cached_values();
}

void ui_PcStatusScreenSecondary_screen_destroy(void)
{
    if (ui_PcStatusScreenSecondary)
    {
        lv_obj_del(ui_PcStatusScreenSecondary);
    }

    ui_PcStatusScreenSecondary = NULL;
    ui_Label2 = NULL;
    ui_LabelPcHost = NULL;
    ui_LabelPcTime = NULL;
    ui_LabelPcLocks = NULL;
    ui_LabelPcNetwork = NULL;
    ui_LabelPcPower = NULL;
    s_LabelPcPerf = NULL;
    s_LabelPcTemp = NULL;
    s_PanelLeft = NULL;
    s_PanelRight = NULL;
    s_LabelTimeValue = NULL;
    s_LabelNetValue = NULL;
    s_LabelUpValue = NULL;
    s_LabelDownValue = NULL;
    s_LabelCpuValue = NULL;
    s_LabelCpuTempValue = NULL;
    s_LabelMemValue = NULL;
    s_LabelDiskValue = NULL;
    s_NetDot = NULL;
    s_BarCpu = NULL;
    s_BarCpuTemp = NULL;
    s_BarMem = NULL;
    s_BarDisk = NULL;
    s_ButtonLeft = NULL;
    s_ButtonRight = NULL;
    s_ButtonEnter = NULL;
    s_ButtonExit = NULL;
}