// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SETTINGSCREEN_H
#define UI_SETTINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingScreen
extern void ui_SettingScreen_screen_init(void);
extern void ui_SettingScreen_screen_destroy(void);
/* 按系统语言刷新标题（0=中文 1=English），由 ui_lang 模块统一调用 */
extern void ui_SettingScreen_apply_language(uint8_t lang);
extern void ui_event_SettingScreen(lv_event_t * e);
extern lv_obj_t * ui_SettingScreen;
extern void ui_event_ButtonLeft5(lv_event_t * e);
extern lv_obj_t * ui_ButtonLeft5;
extern void ui_event_ButtonRight5(lv_event_t * e);
extern lv_obj_t * ui_ButtonRight5;
extern void ui_event_ButtonEnter5(lv_event_t * e);
extern lv_obj_t * ui_ButtonEnter5;
extern lv_obj_t * ui_ButtonExit5;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
